# Generated by Django 5.1.5 on 2025-02-02 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page1', '0001_initial'),
        ('page2', '0001_initial'),
        ('page3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page3.department'),
        ),
        migrations.AddField(
            model_name='emp',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page2.project'),
        ),
    ]
