# Generated by Django 5.1.5 on 2025-02-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
