# Generated by Django 5.1.5 on 2025-02-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
