# Generated by Django 5.1.5 on 2025-02-02 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0002_initial'),
        ('page3', '0002_alter_department_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page1.emp'),
        ),
    ]
