# Generated by Django 5.1.5 on 2025-02-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0003_alter_department_manager_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='manager_id',
        ),
    ]
